FROM python:3.11-slim AS builder

ARG POETRY_VERSION
RUN pip install poetry==$POETRY_VERSION

COPY pyproject.toml poetry.lock ./

RUN poetry export -f requirements.txt --without=dev > requirements.txt \
    && pip wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt

FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /wheels /wheels
RUN pip install --no-cache /wheels/*

COPY . /app/

ENTRYPOINT ["python", "main.py"]
