services:
  prefect-server:
    image: prefect-server-img
    container_name: prefect-server
    build:
      context: .
      dockerfile: Dockerfile-server
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
    ports:
      - "4200:4200"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4200/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 60s

  prefect-task:
    image: prefect-task-img
    container_name: prefect-task
    build:
      context: .
      dockerfile: Dockerfile-task
      args:
        POETRY_VERSION: 1.5.1
    volumes:
      - ./data/processed:/app/data/processed
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      prefect-server:
        condition: service_healthy
